const routes = require("express").Router();
const RegisterUserController = require("../src/app/modules/user/register_user/RegisterUserController");
const AuthenticateUserController = require("../src/app/modules/user/authenticate_user/AuthenticateUserController");
const RefreshTokenController = require("../src/app/modules/user/refresh_token_user/RefreshTokenUserController");
const ResetPasswordUserController = require("../src/app/modules/user/reset_password_user/ResetPassowordUserController");
const IndivualWorkoutsRoutes = require("./routes/manage_individual_workouts");
const TeamWorkoutsRoutes = require("./routes/manage_workouts_by_teams");
const CoursesRouters = require("./routes/courses");
const AthletesRouters = require("./routes/athletes");
const ModalitiesRouters = require("./routes/modalities");
const TeamsRoutes = require("./routes/teams");
const ExercisesTypesRoutes = require("./routes/exercises_types");
const WorkoutExercisesRoutes = require("./routes/manage_exercises");
const permissions = require("../src/app/services/auth_service"); 
const authMiddleware = require("../src/app/middlewares/auth_middleware");
const route = require("./routes/manage_workouts_by_teams");
routes.use('/login', AuthenticateUserController.login);
routes.use('/register', RegisterUserController.register);
routes.use(authMiddleware);
routes.use('/refresh-token', RefreshTokenController.refreshToken);
routes.use('/forgot-password', ResetPasswordUserController.forgotPassword);
routes.use('/reset-password', ResetPasswordUserController.resetPassword);
routes.use(AthletesRouters);
routes.use(CoursesRouters);
routes.use(TeamsRoutes);
routes.use(ModalitiesRouters);
routes.use(IndivualWorkoutsRoutes);
routes.use(TeamWorkoutsRoutes);
route.use(WorkoutExercisesRoutes);
routes.use("/trainer", ExercisesTypesRoutes);
module.exports = routes;